name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
      -
       name: serve
       run: ng serve
      -
       name: Build and push
       uses: docker/build-push-action@v2
       
    
