name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
       - uses: actions/checkout@v2
       - name: Build and Run the Docker image
         run: docker build -t ang-example .
       - 
         name: Login to DockerHub
         uses: docker/login-action@v1 
         with:
          username: reshmaamuthan16 
          password: Reshma2000
       -
         name: Build and push
         id: docker_build
         uses: docker/build-push-action@v2
         with:
          push: true
          tags: user/app:latest
 
    
