name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:

      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: reshmaamuthan16
          password: reshmareshu16
      -
       name: Build and push
       id: docker_build
       uses: docker/build-push-action@v2
       with:
          push: true
          tags: user/app:latest
