name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
       - uses: actions/checkout@v2
       - name: Build  the Docker image
         run: docker build -t ang-example .
       - 
         name: Login to DockerHub
         uses: docker/login-action@v1 
         with:
          username: reshmaamuthan16 
          password: Reshma2000
       -
         name: push the docker image
         uses: actions/checkout@v2
         run: docker push ang-example
 
    
