name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:

      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: reshmaamuthan16
          password: Reshma2000
      -
       name: Build and push
       uses: docker/build-push-action@v2
       
      -
       name: Push docker image
       run: docker push reshmaamutha16/ang-example
